<?php

use App\Http\Controllers\Api\AboutContentController;
use App\Http\Controllers\Api\AboutDashController;
use App\Http\Controllers\Api\AboutSubjectController;
use App\Http\Controllers\Api\AboutTitleController;
use App\Http\Controllers\Api\AccountSwitchController;
use App\Http\Controllers\Api\AnswerController;
use App\Http\Controllers\Api\AssertionController;
use App\Http\Controllers\Api\BankCardController;
use App\Http\Controllers\Api\BlockedUserController;
use App\Http\Controllers\Api\CircleController;
use App\Http\Controllers\Api\ClashController;
use App\Http\Controllers\Api\CommentController;
use App\Http\Controllers\Api\CompetenceController;
use App\Http\Controllers\Api\DomainController;
use App\Http\Controllers\Api\FieldController;
use App\Http\Controllers\Api\FileController;
use App\Http\Controllers\Api\HashtagController;
use App\Http\Controllers\Api\HistoryController;
use App\Http\Controllers\Api\LevelController;
use App\Http\Controllers\Api\MedalController;
use App\Http\Controllers\Api\MessageController;
use App\Http\Controllers\Api\MoneyTransferController;
use App\Http\Controllers\Api\NotificationController;
use App\Http\Controllers\Api\PasswordResetController;
use App\Http\Controllers\Api\PaymentController;
use App\Http\Controllers\Api\PersonalAccessTokenController;
use App\Http\Controllers\Api\PricingController;
use App\Http\Controllers\Api\PricingDescriptionController;
use App\Http\Controllers\Api\PromoCodeController;
use App\Http\Controllers\Api\QuestionController;
use App\Http\Controllers\Api\ReasonController;
use App\Http\Controllers\Api\RecommendationController;
use App\Http\Controllers\Api\ReportController;
use App\Http\Controllers\Api\RoleController;
use App\Http\Controllers\Api\SessionController;
use App\Http\Controllers\Api\SubjectController;
use App\Http\Controllers\Api\SubscriptionController;
use App\Http\Controllers\Api\UserController;
use Illuminate\Support\Facades\Route;

Route::post('users/login', [UserController::class, 'login']);
Route::get('users/username/{username}', [UserController::class, 'findByUsername']);
Route::patch('users/{id}/status', [UserController::class, 'changeStatus']);
Route::patch('users/{id}/password', [UserController::class, 'changePassword']);
Route::patch('users/{id}/type', [UserController::class, 'changeType']);
Route::post('users/{id}/avatar', [UserController::class, 'updateAvatar']);
Route::post('users/{id}/files', [UserController::class, 'addFiles']);
Route::post('users/{id}/restore', [UserController::class, 'restore']);
Route::get('clashs/news-feed/{userId}', [ClashController::class, 'newsFeed']);
Route::post('clashs/{clashId}/invite/{userId}', [ClashController::class, 'inviteMember']);
Route::patch('clashs/{clashId}/react/{userId}', [ClashController::class, 'reactToClash']);
Route::patch('clashs/{clashId}/participate/{userId}', [ClashController::class, 'participate']);
Route::post('password-resets/find-user', [PasswordResetController::class, 'findUser']);
Route::post('password-resets/check-token', [PasswordResetController::class, 'checkToken']);
Route::post('questions/{id}/files', [QuestionController::class, 'addFiles']);
Route::post('assertions/{id}/files', [AssertionController::class, 'addFiles']);
Route::post('answers/{id}/files', [AnswerController::class, 'addFiles']);
Route::post('clashs/{id}/files', [ClashController::class, 'addFiles']);
Route::post('subjects/{id}/files', [SubjectController::class, 'addFiles']);
Route::post('fields/{id}/files', [FieldController::class, 'addFiles']);
Route::post('comments/{id}/files', [CommentController::class, 'addFiles']);
Route::post('domains/{id}/files', [DomainController::class, 'addFiles']);
Route::post('messages/{id}/files', [MessageController::class, 'addFiles']);
Route::post('about-contents/{id}/restore', [AboutContentController::class, 'restore']);
Route::post('about-dashes/{id}/restore', [AboutDashController::class, 'restore']);
Route::post('about-subjects/{id}/restore', [AboutSubjectController::class, 'restore']);
Route::post('about-titles/{id}/restore', [AboutTitleController::class, 'restore']);
Route::post('answers/{id}/restore', [AnswerController::class, 'restore']);
Route::post('assertions/{id}/restore', [AssertionController::class, 'restore']);
Route::post('bank-cards/{id}/restore', [BankCardController::class, 'restore']);
Route::post('blocked-users/{id}/restore', [BlockedUserController::class, 'restore']);
Route::post('circles/{id}/restore', [CircleController::class, 'restore']);
Route::post('clashs/{id}/restore', [ClashController::class, 'restore']);
Route::post('comments/{id}/restore', [CommentController::class, 'restore']);
Route::post('competences/{id}/restore', [CompetenceController::class, 'restore']);
Route::post('domains/{id}/restore', [DomainController::class, 'restore']);
Route::post('fields/{id}/restore', [FieldController::class, 'restore']);
Route::post('files/{id}/restore', [FileController::class, 'restore']);
Route::post('hashtags/{id}/restore', [HashtagController::class, 'restore']);
Route::post('histories/{id}/restore', [HistoryController::class, 'restore']);
Route::post('levels/{id}/restore', [LevelController::class, 'restore']);
Route::post('medals/{id}/restore', [MedalController::class, 'restore']);
Route::post('messages/{id}/restore', [MessageController::class, 'restore']);
Route::post('money-transfers/{id}/restore', [MoneyTransferController::class, 'restore']);
Route::post('notifications/{id}/restore', [NotificationController::class, 'restore']);
Route::post('payments/{id}/restore', [PaymentController::class, 'restore']);
Route::post('pricings/{id}/restore', [PricingController::class, 'restore']);
Route::post('pricing-descriptions/{id}/restore', [PricingDescriptionController::class, 'restore']);
Route::post('promo-codes/{id}/restore', [PromoCodeController::class, 'restore']);
Route::post('questions/{id}/restore', [QuestionController::class, 'restore']);
Route::post('reasons/{id}/restore', [ReasonController::class, 'restore']);
Route::post('recommendations/{id}/restore', [RecommendationController::class, 'restore']);
Route::post('roles/{id}/restore', [RoleController::class, 'restore']);
Route::post('subjects/{id}/restore', [SubjectController::class, 'restore']);

Route::apiResource('users', UserController::class);
Route::apiResource('roles', RoleController::class);
Route::apiResource('password-resets', PasswordResetController::class);
Route::apiResource('personal-access-tokens', PersonalAccessTokenController::class);
Route::apiResource('payments', PaymentController::class);
Route::apiResource('sessions', SessionController::class);
Route::apiResource('levels', LevelController::class);
Route::apiResource('fields', FieldController::class);
Route::apiResource('clashs', ClashController::class);
Route::apiResource('subjects', SubjectController::class);
Route::apiResource('domains', DomainController::class);
Route::apiResource('questions', QuestionController::class);
Route::apiResource('assertions', AssertionController::class);
Route::apiResource('answers', AnswerController::class);
Route::apiResource('comments', CommentController::class);
Route::apiResource('circles', CircleController::class);
Route::apiResource('messages', MessageController::class);
Route::apiResource('files', FileController::class);
Route::apiResource('notifications', NotificationController::class);
Route::apiResource('promo-codes', PromoCodeController::class);
Route::apiResource('about-subjects', AboutSubjectController::class);
Route::apiResource('about-titles', AboutTitleController::class);
Route::apiResource('blocked-users', BlockedUserController::class);
Route::apiResource('about-contents', AboutContentController::class);
Route::apiResource('money-transfers', MoneyTransferController::class);
Route::apiResource('pricings', PricingController::class);
Route::apiResource('pricing-descriptions', PricingDescriptionController::class);
Route::apiResource('medals', MedalController::class);
Route::apiResource('histories', HistoryController::class);
Route::apiResource('subscriptions', SubscriptionController::class);
Route::apiResource('reasons', ReasonController::class);
Route::apiResource('reports', ReportController::class);
Route::apiResource('hashtags', HashtagController::class);
Route::apiResource('competences', CompetenceController::class);
Route::apiResource('recommendations', RecommendationController::class);
Route::apiResource('bank-cards', BankCardController::class);
Route::apiResource('about-dashes', AboutDashController::class);
Route::apiResource('account-switches', AccountSwitchController::class);
